# Generated by Django 4.2.9 on 2024-03-13 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='time',
            field=models.TimeField(default='12:00:00', verbose_name='время выполнения'),
        ),
    ]
